from typing import List, Dict

from .. import HandoffInputData


def remove_all_tools(input_data: HandoffInputData) -> HandoffInputData:
    """Remove messages generated by tool calls from history."""
    filtered = [m for m in input_data.history if m.get("role") != "tool"]
    return HandoffInputData(history=filtered)
